name: Packer

on:
  push_request:
    # Workflow will only be triggered for pull requests on "master" branch
    branches: [ master ]

jobs:
  packer:
    runs-on: ubuntu-20.04
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        env:
          PACKER_LOG: 1
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: us-east-1
          subnet_id: subnet-ac103ce1
          source_ami: ami-03d315ad33b9d49c4
          ami_users: 205467980008
        with:
          command: build
          target: packer/ami.json
        
