name: Validate AMI

on:
  pull_request:
    # Workflow will only be triggered for pull requests on "master" branch
    branches: [ master ]

jobs:
  packer:
    runs-on: ubuntu-20.04
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: packer/ami.json
        
