name: Packer

on:
  pull_request:
    # Workflow will only be triggered for pull requests on "master" branch
    branches: [ master ]

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ami.json

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        env:
          PACKER_LOG: 1
        with:
          command: build
          target: ami.json
        
